### ISSUE TITLE
switch to libgit2 to support advanced git features

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#278]
## Problem 

Multiple (necessary) improvements and features are blocked (https://github.com/inlang/inlang/issues/220, https://github.com/inlang/inlang/issues/252) because the current git implementation (isomorphic-git) does not support advanced git commands like rebasing, sparse checkout and more. 

## Proposal 

Switch the git implementation to [libgit2](https://libgit2.org/) with a WASM binding like https://github.com/petersalomonsen/wasm-git.

## Additional information 

This is a significant effort issue. The git implementation requires touching upon the filesystem, running libgit2 actions in a worker and, generally, libgit2 is lower level. This issue is a good opportunity to move git-related code into the dedicated git-sdk module. This issue should be closed asap as this could lead to breaking changes.  

## Tasks

- [ ] move git-related code from @inlang/website to @inlang/git-sdk
- [x] #322
- [ ] replace isomorphic git implementation with libgit2
- [ ] https://github.com/inlang/inlang/issues/252
- [ ] file system implementation (we roll a custom one?)
- [ ] https://github.com/inlang/inlang/issues/220

**Comment by samuelstroschein** [comment]
From Discord https://discord.com/channels/897438559458430986/1085690231564546068/1085944264757874848

I need to become better and clarifying what is needed + intervene quickly when I believe something might be misunderstood. 

- the blocker that lead to the initiative to switch to libgit2 was rebasing and the foreseen lack of features of isomorphic git 

- shallow clone is supported by isomorphic git. you said repeatedly you are going to try to implement shallow clones. i thought that libgit2 needs hacking to support shallow clones. that's why i did not intervene and said "rebasing is the issue". 

- i focused entirely on sparse checkout to solve cloning related issues, neglacting an intermediate fix of shallow cloning (which is supported in isomorphic git already)

------------------------------------

I think if we can implement rebasing/it is easy to extend isomorphic git to our needs, we are good to proceed with isomorphic git until we hit large obstacles.

**Comment by samuelstroschein** [comment]
Won't be switching to libgit2. We are extending a JS implementation instead.
