### ISSUE TITLE
CLI re-release iteration plan [March 08 - March 12]

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#433]
This issue bundles the efforts to re-release the CLI. Related discussion https://github.com/inlang/inlang/discussions/273.

## Goal

Re-release the CLI to support https://github.com/inlang/inlang/discussions/408 and tremendously simplify getting started with inlang.

## Requirements

- The CLI commands need to be run in the browser/de-coupled from the CLI. 
- The CLI should use sub-commands i.e. `config init`, `lint all` to increase extensibility. 

## Tasks

- [x] #434
- [ ] https://github.com/inlang/inlang/issues/309 
- [ ] `config init` command (with chat gpt)
- [ ] continuous deployment (CI/CD)
- [ ] update getting started documentation 
- [ ] generate configs on the fly in the inlang editor

**Comment by samuelstroschein** [comment]
@jannesblobel starting tomorrow!

**Comment by samuelstroschein** [comment]
moved to #435
