### ISSUE TITLE
cli re-release tracking

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/inlang#477]
I am separating the CLI re-release into smaller PRs. Several things are helpful for other tasks like `@inlang/core/test`.

_Issue copied from https://github.com/inlang/inlang/pull/472_

## Tasks

- [x] #434
- [x] https://github.com/inlang/inlang/issues/309 
- [x] externalize services (to make an API request to OpenAI)
- [x] `config init` command (with chat gpt)
- [x] continuous deployment (CI/CD)
- [x] update getting started documentation 
- [ ] video about automatically generating the config

**Comment by samuelstroschein** [comment]
cli is published
