### ISSUE TITLE
add context tooltip to IDE extension

### ISSUE THREAD

**Issue by felixhaeberle** [inlang/inlang#960]
# Currently

We only display inline annotations at the moment which is already providing value but could do better in terms of displaying more information, such as a link to the editor, multiple languages and a button for machine translation.

# Proposal

Implement a context tooltip like this one 

<img width="351" alt="Bildschirmfoto 2023-06-19 um 16 13 08" src="https://github.com/inlang/inlang/assets/34959078/217e94af-859e-4167-b495-021529372641">

to have a great overview over all the languages and to provide links to other apps / functionalities to have cross-selling effects on the IDE extension.

# Styling

We will comply with the official VS Code styleguide and icons
https://code.visualstudio.com/api/ux-guidelines/overview
https://code.visualstudio.com/api/references/icons-in-labels

# Tasks / Tooltip content & quicklinks

- [x] view all translations for a token.
- [x] change a translation. (quick picks)
- [x] open the browser with the editor exactly at the point of translation.
- [x] ~open the resource file at the point where the respective translation is defined.~ (see https://github.com/inlang/inlang/issues/960#issuecomment-1627773132)

**Comment by samuelstroschein** [comment]
@openscript I am unsure. I would aim for 

- high visibility (users find the feature) 
- easy(ier) to implement

**Comment by felixhaeberle** [comment]
@openscript Yes and no. 😄 I have mixed feelings.

One hand side: the tooltip behavior is pretty common in vs code. vs code itself and a lot of prominent tooling works that way, like typescript errors and vs code "Follow link" option & more. It's also very easy to find.

Other side: The tooltip is a bit "jumpy". Clicking something inside this window can cause to focus loss causing the window to close, but that's not that painful in my opinion, you can simply hover again 😅

**Comment by openscript** [comment]
It isn't hard to implement the tooltip and it will be fun for me to propose a better solution later. :)

**Comment by felixhaeberle** [comment]
let's agree on the following:
- view all translations for a token.
- change a translation. (quick picks)
- open the browser with the editor exactly at the point of translation.
- open the resource file at the point where the respective translation is defined.

@openscript What do you think is the estimate for this task?

**Comment by openscript** [comment]
- view all translations for a token. Estimate with initial setup for the tooltip: 4h
- change a translation. (quick picks) Estimate: 2h
- open the browser with the editor exactly at the point of translation. Estimate: 2h
- open the resource file at the point where the respective translation is defined. Estimate: 2h

Total estimate: 10h

**Comment by felixhaeberle** [comment]
@openscript Let's go 🎉

**Comment by felixhaeberle** [comment]
Icons:

https://code.visualstudio.com/api/references/icons-in-labels

I would pick from the link above:
- notebook-pencil (for editing)
- globe (for jumping to editor)
- go-to-file (juping to reference)

**Comment by openscript** [comment]
Here the icons can be viewed: https://microsoft.github.io/vscode-codicons/dist/codicon.html

**Comment by felixhaeberle** [comment]
EDIT: 

I would pick from the link above:
- edit (for editing)
- globe (for jumping to editor)
- go-to-file (juping to reference)

**Comment by NilsJacobsen** [comment]
What is editing? What will the quickpics show?
The globe was machine translate for i18ally right? Will people remember it wrong, then?
Is there a guideline for the tooltip, too?

**Comment by NilsJacobsen** [comment]
How does the tooltip scale for longer translations? It often happens that translations are multiple lines long.

**Comment by felixhaeberle** [comment]
@NilsJacobsen This was all previously discussed. Sorry, just wanted to ask you for the icon set, but turns out we use the one from VS code instead – so basically nothing to do for you rn ✌️

- Editing is giving the possibility to edit the string in each language via a Quick Pick.
- Globe Icon can be discussed, but I think as this particular Globe Icons as "web" or "remote". A lot of inlang uses haven't use i18n-ally before and if so, they learn it with the first click.
- The text will be truncated (@openscript You decide what fits best.)

**Comment by felixhaeberle** [comment]
@openscript What do you think about the icons selected?

**Comment by felixhaeberle** [comment]
@NilsJacobsen If you are concerned about the `globe` for machine translation: We can use `sparkle` for machine translate in the future, as `sparkle` is currently finding its way to be used as icon for "AI".

I think "sparkle" fits much better for machine translate than "globe". But machine translate is currently not in scoped.

**Comment by NilsJacobsen** [comment]
Aren't u suggesting to use globe for the editor? @felixhaeberle 
Just curious is there a styleguide for the Tooltip, too?
What options will u have in the quicklinks?
Haha sparkle is cool :D But you dropped machinetranslate for now right?

**Comment by felixhaeberle** [comment]
- Yes, globe for editor/"project website", do you have a better opinion in mind?
- VS Code has an official styleguide and icons we should use
- We do not want to introduce our own styling
- Quicklinks: Inline Editing, Jump to file, Go to editor
- We "dropped" machine translate for now. -> It was never included, you raised it but it is not in scope.

@NilsJacobsen **Please read the issue description.** 2/4 of your question are answered there.

**Comment by openscript** [comment]
> EDIT:
> 
> I would pick from the link above:
> 
>     * edit (for editing)
> 
>     * globe (for jumping to editor)
> 
>     * go-to-file (jumping to reference)

I've replaced the globe with the external-link icon for opening the editor. In other products the globe is used to activate machine translation.

![image](https://github.com/inlang/inlang/assets/1105080/c91774f1-9f9b-49e0-be90-52a7eeb1bb7e)

**Comment by openscript** [comment]
For now I decided to show `[missing]` if a message is missing.

![image](https://github.com/inlang/inlang/assets/1105080/9bc81a51-975d-4332-af08-98cfae2ffac1)

**Comment by felixhaeberle** [comment]
@openscript Great work already!!🤩

According to spacing/alignment: Can we create a table like spacing in the tooltip? For example: how does it look like when languages strings "de, en-US" have multiple lengths; how does it behave if the actual messages differ in length?

I would think that a table like spacing where we align the languages, messages and icons on one "visual line" would look best, if this is possible. 

@openscript What do you think about the table like alignment approach?

**Comment by openscript** [comment]
> @openscript Great work already!!star_struck
> 
> According to spacing/alignment: Can we create a table like spacing in the tooltip? For example: how does it look like when languages strings "de, en-US" have multiple lengths; how does it behave if the actual messages differ in length?
> 
> I would think that a table like spacing where we align the languages, messages and icons on their respective vertical "visual line" would look best, if this is possible.
> 
> @openscript What do you think about a table like alignment approach?

It's already a table and behaving as you describe. Its unfortunate that all the cells have the same width in the screenshots above.

**Comment by openscript** [comment]
**Task: open the resource file at the point where the respective translation is defined.**:

This task won't be implemented now. The reasons are:

-  The inlang context doesn't surface the resource file paths, so it takes more effort as initially estimated. It would make sense to change the core and make the messages origin resource path available, as inlang should be the single point of truth on this.
- As a user of the ide extension I have good enough alternatives. I can use the global search with the message id via <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>F</kbd>. Within the global search I can also replace the message id and do some refactoring with it.

**Comment by NilsJacobsen** [comment]
Question: 

Why are we using quick picks when you only have the two options that are also there in the icons? Or the other way around, why are we using three icons when we could only use quick picks with the options? 

> VS Code has an official styleguide and icons we should use

Do you have a link? I agree let's keep the styling of vscode

> We "dropped" machine translate for now. -> It was never included, you raised it but it is not in scope. 

I know that was not a question.

@openscript great work 👍

**Comment by felixhaeberle** [comment]
> Why are we using quick picks
Because that's the way you edit fast&easy & also respect the UX Guidelines of VS Code.

Updated the issue description with links.

**Comment by NilsJacobsen** [comment]
Don't get me wrong, I totally agree that we align with vscode. Just asking about the duplication.

**Comment by felixhaeberle** [comment]
I guess I don't know what you are referring to with duplication. Can you elaborate?

**Comment by NilsJacobsen** [comment]
You could either use the icons or press the edit icon and use QuickPics. While having only two actions, that seems a bit duplicated. Is it standard to have the actions as icons and in the QuickPics? We could also have only an arrow that opens the QuickPics for example—just a thought.

**Comment by felixhaeberle** [comment]
🎉
